"""ajuste relacionamento tabela-colunas

Revision ID: 294763194919
Revises: 85c81c2d377d
Create Date: 2025-10-03 11:24:26.500028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294763194919'
down_revision = '85c81c2d377d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_colunas')
    with op.batch_alter_table('colunas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tabela_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_colunas_tabela', 'tabela', ['tabela_id'], ['id'])

    with op.batch_alter_table('tabela', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Colunas_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabela', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Colunas_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'colunas', ['Colunas_id'], ['id'])

    with op.batch_alter_table('colunas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_colunas_tabela', type_='foreignkey')
        batch_op.drop_column('tabela_id')

    op.create_table('_alembic_tmp_colunas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome_coluna', sa.VARCHAR(), nullable=False),
    sa.Column('tipo_dado', sa.VARCHAR(), nullable=False),
    sa.Column('tabela_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['tabela_id'], ['tabela.id'], name='fk_colunas_tabela'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
