"""tentando fazer salvar no bd

Revision ID: 2d02ea0129a8
Revises: 294763194919
Create Date: 2025-10-06 08:28:00.617560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d02ea0129a8'
down_revision = '294763194919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabela', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dag_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('origem_id', sa.Integer(), nullable=False))
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_tabela_origem', 'origem', ['origem_id'], ['id'])
        batch_op.create_foreign_key('fk_tabela_dag', 'dag', ['dag_id'], ['id'])
        batch_op.drop_column('Dag_id')
        batch_op.drop_column('Origem_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabela', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Origem_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('Dag_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_tabela_dag', type_='foreignkey')
        batch_op.drop_constraint('fk_tabela_origem', type_='foreignkey')
        batch_op.create_foreign_key(None, 'dag', ['Dag_id'], ['id'])
        batch_op.create_foreign_key(None, 'origem', ['Origem_id'], ['id'])
        batch_op.drop_column('origem_id')
        batch_op.drop_column('dag_id')

    # ### end Alembic commands ###
