"""Criando tabelas novas

Revision ID: 85c81c2d377d
Revises: 6d2fd13a028c
Create Date: 2025-10-02 16:08:09.002226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c81c2d377d'
down_revision = '6d2fd13a028c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colunas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_coluna', sa.String(), nullable=False),
    sa.Column('tipo_dado', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dag', sa.String(), nullable=False),
    sa.Column('schedule', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('origem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sistema_origem', sa.String(), nullable=False),
    sa.Column('tabela_origem', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tabela',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_tabela', sa.String(), nullable=False),
    sa.Column('descricao_tabela', sa.String(), nullable=True),
    sa.Column('esquema', sa.String(), nullable=False),
    sa.Column('Dag_id', sa.Integer(), nullable=False),
    sa.Column('Colunas_id', sa.Integer(), nullable=False),
    sa.Column('Origem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Colunas_id'], ['colunas.id'], ),
    sa.ForeignKeyConstraint(['Dag_id'], ['dag.id'], ),
    sa.ForeignKeyConstraint(['Origem_id'], ['origem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('foto')
        batch_op.drop_column('ultimo_visto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_visto', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('foto', sa.VARCHAR(), nullable=True))

    op.drop_table('tabela')
    op.drop_table('origem')
    op.drop_table('dag')
    op.drop_table('colunas')
    # ### end Alembic commands ###
